package:
  name: "javatest"
  version: "1.0.0"

build:
  number: 0
  noarch: generic

requirements:
  run:
    - python
    - openjdk

test:
  commands:
    - HelitronScanner --help

about:
  home: https://github.com/DerKevinRiehl
  license: BSD
  license_family: BSD
  summary: "javatest summary"
  doc_url: https://github.com/DerKevinRiehl
  dev_url: https://github.com/DerKevinRiehl
